name:                elynx-tools
version:             0.0.1
github:              "dschrempf/elynx"
license:             GPL-3
license-file:        LICENSE
author:              "Dominik Schrempf"
maintainer:          "dominik.schrempf@gmail.com"
copyright:           "Dominik Schrempf (2019)"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Tools for ELynx
category:            Bioinformatics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dschrempf/elynx>.

ghc-options:
  - -Wall
  - -O2
  # # LLVM 6.0 not available for Arch anymore.
  # - -fllvm

dependencies:
  - aeson
  - async
  - base
  - bytestring
  - containers
  - cryptohash-sha256
  # - data-memocombinators
  - deepseq
  - fast-logger
  - hmatrix
  - lifted-base
  # - integration
  # - lens
  # - math-functions
  - matrices
  - megaparsec
  - monad-logger
  - monad-control
  # - monad-parallel
  - mwc-random
  - optparse-applicative
  - parallel
  - primitive
  # - statistics
  - template-haskell
  - text
  - time
  - transformers
  - transformers-base
  - vector
  # - word8
  - zlib

library:
  source-dirs: src
