name:                elynx-tools
version:             0.2.3
github:              "dschrempf/elynx"
license:             GPL-3.0-or-later
license-file:        LICENSE
author:              "Dominik Schrempf"
maintainer:          "dominik.schrempf@gmail.com"
copyright:           "Dominik Schrempf (2020)"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Tools for ELynx
category:            Bioinformatics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dschrempf/elynx>.

ghc-options:
  - -Wall
  - -fllvm

library:
  source-dirs: src
  exposed-modules: ELynx.Tools
  dependencies:
    - aeson
    - async
    - base >=4.7 && <5
    - base16-bytestring
    - bytestring
    - containers
    - cryptohash-sha256
    - deepseq
    - directory
    - fast-logger
    - hmatrix
    - matrices
    - megaparsec
    - monad-logger
    - monad-control
    - mwc-random
    - optparse-applicative
    - parallel
    - primitive
    - template-haskell
    - text
    - time
    - transformers
    - transformers-base
    - vector
    - zlib
  generated-other-modules: Paths_elynx_tools
