name:                evomod
version:             0.1.0.2
github:              "dschrempf/evomod"
license:             GPL-3
author:              "Dominik Schrempf"
maintainer:          "dominik.schrempf@gmail.com"
copyright:           "Dominik Schrempf (2018)"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Read and modify molecular sequence data in a reproducible way.
category:            Bioinformatics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dschrempf/evomod>.

ghc-options:
  - -Wall
  - -O2
  - -fllvm

dependencies:
  - base
  - bytestring
  - containers
  - hmatrix
  - lens
  - math-functions
  - megaparsec
  - mwc-random
  - optparse-applicative
  - primitive
  - text
  - vector
  - word8
  - zlib

library:
  source-dirs: src

# Defaults for executables.
_defaults: &defaults
  # Development options.
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -eventlog
  # # Production options.
  # ghc-options:
  # - -threaded
  
executables:
  evomod-seq:
    <<: *defaults
    main:                Main.hs
    source-dirs:         app/EvoModSeq
    dependencies:
      - evomod

tests:
  evomod-test:
    <<: *defaults
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - evomod
    - hspec
    - hspec-megaparsec
