name:                tlynx
version:             0.3.1
github:              "dschrempf/elynx"
license:             GPL-3.0-or-later
license-file:        LICENSE
author:              "Dominik Schrempf"
maintainer:          "dominik.schrempf@gmail.com"
copyright:           "Dominik Schrempf (2020)"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Handle phylogenetic trees
category:            Bioinformatics
description:
  Examine, compare, and simulate phylogenetic trees in a reproducible way.
  Please see the README on GitHub at <https://github.com/dschrempf/elynx>.

ghc-options:
  - -Wall
  - -fllvm

library:
  source-dirs: src
  dependencies:
    - aeson
    - attoparsec
    - lifted-async
    - base >=4.7 && <5
    - bytestring
    - comonad
    - containers
    - elynx-tools
    - elynx-tree
    - gnuplot
    - monad-logger
    - mwc-random
    - optparse-applicative
    - parallel
    - statistics
    - text
    - transformers
    - vector
  generated-other-modules: Paths_tlynx

executables:
  tlynx:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >=4.7 && <5
      - tlynx
