name:                tlynx
version:             0.1.0
github:              "dschrempf/elynx"
license:             GPL-3
license-file:        LICENSE
author:              "Dominik Schrempf"
maintainer:          "dominik.schrempf@gmail.com"
copyright:           "Dominik Schrempf (2020)"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Handle phylogenetic trees
category:            Bioinformatics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Examine, compare, and simulate phylogenetic trees in a reproducible way.
  Please see the README on GitHub at <https://github.com/dschrempf/elynx>.

ghc-options:
  - -Wall
  - -O2
  # # LLVM 6.0 not available for Arch anymore.
  # - -fllvm

dependencies:
  - aeson
  - array
  - lifted-async
  - base
  - bytestring
  - comonad
  - containers
  # - data-memocombinators
  # - distribution
  - gnuplot
  # - hstats
  # - hmatrix
  # - integration
  # - lens
  - math-functions
  # - matrices
  - megaparsec
  - monad-logger
  - MonadRandom
  - mwc-random
  - optparse-applicative
  - parallel
  - primitive
  - scientific
  - QuickCheck
  - quickcheck-instances
  - statistics
  - text
  - transformers
  - vector
  # - word8
  # - zlib

library:
  source-dirs: src
  dependencies:
    - elynx-tools
    - elynx-tree

executables:
  tlynx:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      # Deactivate eventlog for production.
      - -eventlog
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - elynx-tools
      - tlynx
