name:                evomod-tree
version:             0.4
github:              "dschrempf/evomod"
license:             GPL-3
author:              "Dominik Schrempf"
maintainer:          "dominik.schrempf@gmail.com"
copyright:           "Dominik Schrempf (2018)"

extra-source-files:
- README.org
- ChangeLog.org

# Metadata used when publishing your package
synopsis:            Handle phylogenetic trees in a reproducible way.
category:            Bioinformatics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.org file.
description:         Please see the README on GitHub at <https://github.com/dschrempf/evomod>.

ghc-options:
  - -Wall
  - -O2
  # # LLVM 6.0 not available for Arch anymore.
  # - -fllvm

dependencies:
  - lifted-async
  - base
  - bytestring
  - containers
  # - data-memocombinators
  # - distribution
  # - hstats
  # - hmatrix
  # - integration
  # - lens
  - math-functions
  # - matrices
  - megaparsec
  - mwc-random
  - optparse-applicative
  - parallel
  - primitive
  - statistics
  - transformers
  - vector
  # - word8
  # - zlib

library:
  source-dirs: src
  dependencies:
    - evomod-tools

# Defaults for executables.
_defaults: &defaults
  # Development options.
  ghc-options:
    # Deactivate eventlog for production.
    - -eventlog
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

executables:
  tree-ana:
    <<: *defaults
    main:                Main.hs
    source-dirs:         app/TreeAna
    dependencies:
      - evomod-tools
      - evomod-tree

  tree-dist:
    <<: *defaults
    main:                Main.hs
    source-dirs:         app/TreeDist
    dependencies:
      - evomod-tools
      - evomod-tree

  tree-sim:
    <<: *defaults
    main:                Main.hs
    source-dirs:         app/TreeSim
    dependencies:
      - evomod-tools
      - evomod-tree

tests:
  tree-test:
    <<: *defaults
    main:                Spec.hs
    source-dirs:         test
    dependencies:
      - evomod-tree
      - evomod-tools
      - hspec
      - hspec-megaparsec
