name:                evomod-seq
version:             0.3
github:              "dschrempf/evomod"
license:             GPL-3
author:              "Dominik Schrempf"
maintainer:          "dominik.schrempf@gmail.com"
copyright:           "Dominik Schrempf (2019)"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Read and modify molecular sequence data in a reproducible way.
category:            Bioinformatics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dschrempf/evomod>.

ghc-options:
  - -Wall
  - -O2
  - -fllvm

dependencies:
  - async
  - base
  - bytestring
  - containers
  - data-memocombinators
  - hmatrix
  - integration
  - lens
  - math-functions
  - matrices
  - megaparsec
  - mwc-random
  - optparse-applicative
  - parallel
  - primitive
  - statistics
  - transformers
  - vector
  - vector-th-unbox
  - word8
  # - zlib

library:
  source-dirs: src
  dependencies:
    - evomod-tools
    - evomod-tree

# Defaults for executables.
_defaults: &defaults
  # Development options.
  ghc-options:
    # Deactivate eventlog for production.
    - -eventlog
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

executables:
  seq-ana:
    <<: *defaults
    main:                Main.hs
    source-dirs:         app/SeqAna
    dependencies:
      - evomod-seq
      - evomod-tools

  seq-sim:
    <<: *defaults
    main:                Main.hs
    source-dirs:         app/SeqSim
    dependencies:
      - evomod-seq
      - evomod-tools
      - evomod-tree

tests:
  seq-test:
    <<: *defaults
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - evomod-seq
    - evomod-tools
    - evomod-tree
    - hspec
    - hspec-megaparsec
