name:                slynx
version:             0.2.1
github:              "dschrempf/elynx"
license:             GPL-3.0-or-later
license-file:        LICENSE
author:              "Dominik Schrempf"
maintainer:          "dominik.schrempf@gmail.com"
copyright:           "Dominik Schrempf (2020)"
# TODO: Explicit definition of the version of the cabal file should not be
# necessary, but see https://github.com/sol/hpack/issues/384.
verbatim:
  cabal-version: 3.0

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Handle molecular sequences
category:            Bioinformatics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Examine, modify, and simulate molecular sequences in a reproducible way.
  Please see the README on GitHub at <https://github.com/dschrempf/elynx>.

ghc-options:
  - -Wall
  # XXX: Try without -O2, but has to be added back if binaries are too slow.
  # - -O2
  - -fllvm

dependencies:
  - async
  - base
  - bytestring
  - containers
  - hmatrix
  - megaparsec
  - monad-logger
  - mwc-random
  - optparse-applicative
  - scientific
  - text
  - transformers
  - vector

library:
  source-dirs: src
  dependencies:
    - elynx-markov
    - elynx-seq
    - elynx-tools
    - elynx-tree
  generated-other-modules: Paths_slynx

executables:
  slynx:
    main:                Main.hs
    source-dirs:         app
    generated-other-modules: Paths_slynx
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - elynx-seq
      - elynx-tools
      - slynx
