name:                slynx
version:             0.3.0
github:              "dschrempf/elynx"
license:             GPL-3.0-or-later
license-file:        LICENSE
author:              "Dominik Schrempf"
maintainer:          "dominik.schrempf@gmail.com"
copyright:           "Dominik Schrempf (2020)"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Handle molecular sequences
category:            Bioinformatics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Examine, modify, and simulate molecular sequences in a reproducible way.
  Please see the README on GitHub at <https://github.com/dschrempf/elynx>.

ghc-options:
  - -Wall
  - -fllvm

library:
  source-dirs: src
  dependencies:
    - async
    - base >=4.7 && <5
    - bytestring
    - containers
    - elynx-markov
    - elynx-seq
    - elynx-tools
    - elynx-tree
    - hmatrix
    - megaparsec
    - monad-logger
    - mwc-random
    - optparse-applicative
    - scientific
    - text
    - transformers
    - vector
  generated-other-modules: Paths_slynx

executables:
  slynx:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >=4.7 && <5
      - elynx-seq
      - elynx-tools
      - slynx
