name:                slynx
version:             0.1.0
github:              "dschrempf/elynx"
license:             GPL-3
license-file:        LICENSE
author:              "Dominik Schrempf"
maintainer:          "dominik.schrempf@gmail.com"
copyright:           "Dominik Schrempf (2020)"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Handle molecular sequences
category:            Bioinformatics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Examine, modify, and simulate molecular sequences in a reproducible way.
  Please see the README on GitHub at <https://github.com/dschrempf/elynx>.

ghc-options:
  - -Wall
  - -O2
  - -fllvm

dependencies:
  - async
  - base
  - bytestring
  - containers
  - data-memocombinators
  - hmatrix
  - integration
  - math-functions
  - matrices
  - megaparsec
  - monad-logger
  - mwc-random
  - optparse-applicative
  - parallel
  - primitive
  - scientific
  - statistics
  - text
  - transformers
  - vector
  - vector-th-unbox
  - word8

library:
  source-dirs: src
  dependencies:
    - elynx-markov
    - elynx-seq
    - elynx-tools
    - elynx-tree

executables:
  slynx:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fwrite-ide-info
    dependencies:
      - elynx-seq
      - elynx-tools
      - slynx
