name:                elynx-seq
version:             0.5.2
github:              "dschrempf/elynx"
license:             GPL-3
author:              "Dominik Schrempf"
maintainer:          "dominik.schrempf@gmail.com"
copyright:           "Dominik Schrempf (2019)"

extra-source-files:
- README.org
- ChangeLog.org

# Metadata used when publishing your package
synopsis:            Examine, modify, and simulate molecular sequence data in a reproducible way.
category:            Bioinformatics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.org file.
description:         Please see the README on GitHub at <https://github.com/dschrempf/elynx>.

ghc-options:
  - -Wall
  - -O2
  # # LLVM 6.0 not available for Arch anymore.
  # - -fllvm

dependencies:
  - async
  - base
  - bytestring
  - containers
  - data-memocombinators
  - hmatrix
  - integration
  - lens
  - math-functions
  - matrices
  - megaparsec
  - mwc-random
  - optparse-applicative
  - parallel
  - primitive
  - statistics
  - transformers
  - vector
  - vector-th-unbox
  - word8
  # - zlib

library:
  source-dirs: src
  dependencies:
    - elynx-tree
    - elynx-tools

tests:
  seq-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      # Deactivate eventlog for production.
      - -eventlog
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
    - elynx-seq
    - elynx-tools
    - elynx-tree
    - hspec
    - hspec-megaparsec
