name:                elynx-tree
version:             0.2.0
github:              "dschrempf/elynx"
license:             GPL-3
license-file:        LICENSE
author:              "Dominik Schrempf"
maintainer:          "dominik.schrempf@gmail.com"
copyright:           "Dominik Schrempf (2020)"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Handle phylogenetic trees
category:            Bioinformatics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Examine, compare, and simulate phylogenetic trees in a reproducible way.
  Please see the README on GitHub at <https://github.com/dschrempf/elynx>.

ghc-options:
  - -Wall
  - -O2
  - -fllvm

dependencies:
  - base
  - bytestring
  - containers
  - math-functions
  - megaparsec
  - mwc-random
  - primitive
  - statistics

library:
  source-dirs: src
  dependencies:
    - elynx-tools

benchmarks:
  tree-bench:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - elynx-tools
      - elynx-tree
      - criterion

tests:
  tree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - elynx-tools
      - elynx-tree
      - hspec
      - hspec-megaparsec
      - QuickCheck
      - quickcheck-instances
