name:                evolib-tree
version:             0.5.1
github:              "dschrempf/evomod"
license:             GPL-3
author:              "Dominik Schrempf"
maintainer:          "dominik.schrempf@gmail.com"
copyright:           "Dominik Schrempf (2018)"

extra-source-files:
- README.org
- ChangeLog.org

# Metadata used when publishing your package
synopsis:            Handle phylogenetic trees in a reproducible way.
category:            Bioinformatics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.org file.
description:         Please see the README on GitHub at <https://github.com/dschrempf/evomod>.

ghc-options:
  - -Wall
  - -O2
  # # LLVM 6.0 not available for Arch anymore.
  # - -fllvm

dependencies:
  - lifted-async
  - base
  - bytestring
  - containers
  # - data-memocombinators
  # - distribution
  # - hstats
  # - hmatrix
  # - integration
  # - lens
  - math-functions
  # - matrices
  - megaparsec
  - mwc-random
  - optparse-applicative
  - parallel
  - primitive
  - QuickCheck
  - quickcheck-instances
  - statistics
  - transformers
  - vector
  # - word8
  # - zlib

library:
  source-dirs: src
  dependencies:
    - evolib-tools

tests:
  tree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      # Deactivate eventlog for production.
      - -eventlog
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - evolib-tools
      - evolib-tree
      - hspec
      - hspec-megaparsec
